### ISSUE TITLE
kurs bni

### ISSUE THREAD

**Issue by sprabowo** [bachors/Kurs-API#1]
sepertinya kurs bninya salah grab om. itu kayaknya malah yang AUD.

**Comment by bachors** [comment]
o iya gan trimakasih atas pemberitahuan.y, harus.y pilih yang mana ya gan? soalnya saya kurang fahan apa itu AUD dan yg lainya.

**Comment by sprabowo** [comment]
AUD = Australian Dollar om. kalau BNI USDnya ada di paling bawah.

**Comment by bachors** [comment]
sudah om :+1:
